version: '3.3'

volumes:
    data:
    config:

services:
  sftp:
    image: ${SFTP_IMAGE}:${SFTP_VERSION}
    ports:
        - "${SFTP_PORT}:22"
    volumes:
        - config:/app/config/sftp.json:ro
        - data:/home/demo/sftp
    networks:
        - sftp_network

networks:
    sftp_network:
        driver: bridge
